[package]
name = "birthdays"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
chrono = "0.4.42"
tokio = { version = "1.48.0", features = ["full"] }
tower = "0.5.2"
tower-http = "0.6.8"
